<?php
    $products = [
        [
            'product_id' => '1',
            'product_name' => 'abalone',
            'price' => '20',
            'image' => 'img/h0888001_10018525_190830050853_01_1200.jpg',
            'label' => 'sale',
            'rating' => '4.5',
            'best_seller_label' => 'All',
            'quantity' => '1',
        ],
        [
            'product_id' => '2',
            'product_name' => 'Lion & Globe Pure Canola Oil',
            'price' => '10',
            'image' => 'img/gas.jpeg',
            'label' => 'sale',
            'rating' => '4.5',
            'best_seller_label' => 'Best Sellers',
            'quantity' => '1',
        ],
        [
            'product_id' => '3',
            'product_name' => 'Shampoo',
            'price' => '10',
            'image' => 'img/hair.jpeg',
            'label' => 'sale',
            'rating' => '4.5',
            'best_seller_label' => 'Featured',
            'quantity' => '1',
        ],
        [
            'product_id' => '4',
            'product_name' => 'rice',
            'price' => '15',
            'image' => 'img/rice.jpeg',
            'label' => 'sale',
            'rating' => '4.5',
            'best_seller_label' => 'New Arrival',
            'quantity' => '1',
        ],
        [
            'product_id' => '5',
            'product_name' => 'Coren Magro Iberico',
            'price' => '16',
            'image' => 'img/lid.jpeg',
            'label' => 'sale',
            'rating' => '4.5',
            'best_seller_label' => 'New Arrival',
            'quantity' => '1',
        ],
        [
            'product_id' => '6',
            'product_name' => 'cola',
            'price' => '10',
            'image' => 'img/cola.jpeg',
            'label' => 'sale',
            'rating' => '4.5',
            'best_seller_label' => 'Best Sellers',
            'quantity' => '1',
        ],
    ]
?>